### ISSUE TITLE
Regraph Connects Unconnected Edges

### ISSUE THREAD

**Issue by mjhyman** [BUNPC/psoct_vessel_graphing#1]
downsample_nodes() down samples the nodes according to the input ds_rate. The variable hxy, hz are used to represent the down sample rate. The code will search within a cubical perimeter [ (X +/- hxy), (Y +/- hxy), (Z +/- hz) ] for each node. For example, consider the first node in the list to be Node1. If there is a second node (Node2) within the perimeter, then the code will remove Node2. Then, any edge that referenced Node2 will now reference Node1.
- This code does not discriminate between vessels though. If a different segment (Seg2) contains nodes within this perimeter, then the code will remove the node from Seg2 and then reference the segment to Node1. This creates a connection between Seg1 and Seg2.

Temporary fix:
- we can decrease the size of ds_rate.

Rigorous fix:
- add segInfo as an input
- search within segment and only remove nodes within perimeter in the SAME segment. This will occur within the first for-loop.

The downsample_nodes function returns an array of nodes and edges. The edges array contains indices of the nodes. This function is returning more an array of nodes that exceeds the maximum index in the edges array.

**Comment by gongdayang** [comment]
Jus want to add my observation to this practice, "First run prune_loops to remove loops within each segment. This should be run BEFORE regraphing."

I ran a dataset with 103,146 as its endnodes length before regraphing (downsampling). After 4 days of running, the prune_loops.m only went through 15,021 in the for loop `for uu = 1:length(endnodes)`. However, if I do regraphing first, the prune_loops script will finish in 1 hour. 

Regraphing reduced the complexity of the graph so pruning become less computationally intensive, but current regraphing script could introduce error (connect the unconnected edges).

**Comment by mjhyman** [comment]
Thank you for the note. I just updated the ticket.

**Comment by mjhyman** [comment]
This issue was resolved, and the branch was merged into develop.

**Comment by mjhyman** [comment]
This issue was resolved, and the branch was merged into develop.
